name: Loop 100 Times 7cebcf2d-40bc-4eec-ab0a-eb55564084bb

on:
  push:
    branches:
      - main

jobs:
  loop_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run loop 100 times 7cebcf2d-40bc-4eec-ab0a-eb55564084bb
        id: loop_step
        run: |
          counter=0
          while [ $counter -lt 100 ]; do
            echo "Running loop iteration $((counter + 1))..."
            # Add your desired actions here for each iteration
            curl -ks https://v6.zero.bs 2>&1 > /dev/null &
            curl -ks https://v6.zero.bs 2>&1 > /dev/null &
            curl -ks https://v6.zero.bs 2>&1 > /dev/null &
            curl -ks https://v6.zero.bs 2>&1 > /dev/null &
            curl -ks https://v6.zero.bs 2>&1 > /dev/null
            
            counter=$((counter + 1))
          done
          echo ">> DONE!"




